# Generated by Django 5.1.6 on 2025-03-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_comment_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='article',
            name='public_date',
            field=models.DateTimeField(),
        ),
    ]
